[package]
name = "tarsmith"
version = "0.3.0"
edition = "2024"
license = "MIT"
authors = ["sharifmdathar"]
description = "A simple, interactive installer for tar archives"
repository = "https://github.com/sharifmdathar/tarsmith"

[dependencies]
dirs = "6.0.0"
